language: node_js
node_js:
  - "v12.8.1"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build:example
#  - npm install codecov -g
#after_success:
#  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: examples/dist
  on:
    branch: master
